FROM openjdk:21-jdk-slim

WORKDIR /app


COPY ../../mvnw .
COPY ../../mvnw.cmd .
COPY ../../pom.xml .
COPY ../../.mvn .mvn


COPY ../pom.xml ./point/pom.xml
COPY ../../user/pom.xml ./user/pom.xml
COPY ../../statistic/pom.xml ./statistic/pom.xml
COPY ../../common/pom.xml ./common/pom.xml


COPY ../../point/src ./point/src
COPY ../../common/src ./common/src


RUN chmod +x mvnw


RUN ./mvnw clean package -pl point -am -DskipTests


RUN mkdir -p /app/target


RUN cp point/target/*.jar /app/target/app.jar


EXPOSE 8091 8062


CMD ["java", "-jar", "/app/target/app.jar"] 